=== mehradh/mobihacker/js-2-cards/data.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- Card -->
  <xs:complexType name="Card">
    <xs:sequence minOccurs="1">
      <xs:element maxOccurs="unbounded" name="p" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="title" type="xs:string" use="required" />
  </xs:complexType>
  
  <!-- Document -->
  <xs:complexType name="Document">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element maxOccurs="unbounded" name="card" type="Card" />
    </xs:sequence>
  </xs:complexType>
  
  <!-- root element -->
  <xs:element name="doc" type="Document" />
</xs:schema>

=== mehradh/mobihacker/js-2-cards/data.xml
<?xml version="1.0" encoding="utf-8" ?>
<doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="data.xsd" xsi:schemaLocation=".\ data.xsd">
  <card title="What's Haskell?">
    <p>Haskell is a purely functional programming language. In imperative languages you get things done by giving the computer a sequence of tasks and then it executes them. While executing them, it can change state. For instance, you set variable a to 5 and then do some stuff and then set it to something else. You have control flow structures for doing some action several times.</p>
    <p> In purely functional programming you don't tell the computer what to do as such but rather you tell it what stuff is. The factorial of a number is the product of all the numbers from 1 to that number, the sum of a list of numbers is the first number plus the sum of all the other numbers, and so on. You express that in the form of functions. You also can't set a variable to something and then set it to something else later. If you say that a is 5, you can't say it's something else later because you just said it was 5.</p>
    <p>So in purely functional languages, a function has no side-effects. The only thing a function can do is calculate something and return it as a result. </p>
  </card>
  <card title="Lazy">
    <p>Haskell is lazy. That means that unless specifically told otherwise, Haskell won't execute functions and calculate things until it's really forced to show you a result. That goes well with referential transparency and it allows you to think of programs as a series of transformations on data.</p>
    <p>It also allows cool things such as infinite data structures. Say you have an immutable list of numbers xs = [1,2,3,4,5,6,7,8] and a function doubleMe which multiplies every element by 2 and then returns a new list. If we wanted to multiply our list by 8 in an imperative language and did doubleMe(doubleMe(doubleMe(xs))), it would probably pass through the list once and make a copy and then return it.</p>
  </card>
  <card title="Typed">
    <p>Haskell is statically typed. When you compile your program, the compiler knows which piece of code is a number, which is a string and so on. That means that a lot of possible errors are caught at compile time. If you try to add together a number and a string, the compiler will whine at you. Haskell uses a very good type system that has type inference.</p>
    <p>hat means that you don't have to explicitly label every piece of code with a type because the type system can intelligently figure out a lot about it. If you say a = 5 + 4, you don't have to tell Haskell that a is a number, it can figure that out by itself. </p>
  </card>
</doc>
